version: "3"
services:
  bot_template:
    image: bot_template
    build:
      context: .
      dockerfile: 'BOT_TEMPLATE/Dockerfile'
    container_name: 'BOT_TEMPLATE'
    ports:
      - '11000:11000'
    restart: always
    healthcheck:
      test: ["CMD", "perl", "healthcheck.pl", "", "healthchecker", "--botname", "BOT_TEMPLATE", "--port", "11000"]
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 2s

networks:
  default:
    name: alloxentric.com
